function GARCH_BackTestReturns = modelTimeSeries(BackTestReturns)
% GARCH_BackTestReturns = modelTimeSeries(BackTestReturns)
% returns an estimated model. This code recreates the estimated model
% produced in the Econometric Modeler app. Use the code below to estimate
% the same model, or estimate a model with the same parameters on a new set
% of data.
%
%	Input:
%		BackTestReturns: A numeric matrix with the same number of columns as the data imported into the app
%
%	Output:
%		GARCH_BackTestReturns: The model containing estimated parameters
%
% Auto-generated by MATLAB Version 9.4 (R2018a) and Econometrics Toolbox Version 5.0 on 11-Aug-2018 17:58:19

BackTestReturns = BackTestReturns(:,1);

%% Estimate a GARCH Model of time series BackTestReturns
GARCH_BackTestReturns = garch('Offset',0,'GARCHLags',1,'ARCHLags',1,'Distribution','Gaussian');
GARCH_BackTestReturns = estimate(GARCH_BackTestReturns,BackTestReturns,'Display','off');

end