function GARCH_PSSGDiffSeasonalDiffDetrend = modelTimeSeries(DataTable)
%%Time Series Modeling Using the Econometric Modeler
% This code recreates the estimated model produced in the Econometric Modeler app. Use the code below to estimate the same model, or estimate a model with the same parameters on a new set of data.
%
%Input: A timetable with the same variables as the table imported into the app (DataTable)
%
%Output: The model containing estimated parameters (GARCH_PSSGDiffSeasonalDiffDetrend)
%
%Auto-generated by MATLAB (R2023a) and Econometrics Toolbox Version 6.2 on 24-Aug-2023 14:15:46
PSSG = DataTable.PSSG;

%% First Order Difference
% Perform a first order difference on time series PSSG
PSSGDiff = [NaN; diff(PSSG)];

%% Seasonal Difference
% Perform a seasonal difference on time series PSSGDiff with periodicity 12
LagPoly = LagOp({1,-1},'Lags',[0,12]);
PSSGDiffSeasonalDiff = [nan(12,1); filter(LagPoly,PSSGDiff)];


%% Detrend
% Remove linear trend from PSSGDiffSeasonalDiff
validIdx = find(~isnan(PSSGDiffSeasonalDiff));
PSSGDiffSeasonalDiffDetrend = [nan(validIdx(1)-1,1), detrend(PSSGDiffSeasonalDiff(validIdx)), nan(length(PSSGDiffSeasonalDiff)-validIdx(end),1)];

%% Generalized Autoregressive Conditional Heteroscedasticity Model
% Estimate a GARCH Model of PSSGDiffSeasonalDiffDetrend
GARCH_PSSGDiffSeasonalDiffDetrend = garch('Offset',0,'GARCHLags',1,'ARCHLags',1,'Distribution','Gaussian');
GARCH_PSSGDiffSeasonalDiffDetrend = estimate(GARCH_PSSGDiffSeasonalDiffDetrend,PSSGDiffSeasonalDiffDetrend,'Display','off');
end